name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: nixbuild/nix-quick-install-action@v26
    - uses: nix-community/cache-nix-action@v3
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
        restore-keys: |
          ${{ runner.os }}-nix-
    - uses: HatsuneMiku3939/direnv-action@v1
      with:
        direnvVersion: 2.32.1
    - name: Run checks
      run: go test ./...
